//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labtestportal.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        public int person_id { get; set; }
        public int state_id { get; set; }
        public int gender_id { get; set; }
        [Required(ErrorMessage = "Please enter first name.")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "Please enter last name.")]
        public string Last_Name { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual Pers_Gender Pers_Gender { get; set; }
        public virtual State State { get; set; }
    }
}
